{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "26410b7a",
   "metadata": {},
   "source": [
    "# üîß ML Hyperparameter Tuning - Fraud Detection\n",
    "This notebook uses `GridSearchCV` and `RandomizedSearchCV` to tune the hyperparameters of Logistic Regression, Random Forest, XGBoost, and LightGBM models."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0c3ef6f4",
   "metadata": {},
   "source": [
    "## üì• Step 1: Load and Prepare Data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "93c2361f",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "\n",
    "# Load enhanced dataset\n",
    "df = pd.read_csv(\"enhanced_online_fraud_dataset.csv\")\n",
    "\n",
    "# Features and label\n",
    "X = df.drop(columns=['isFraud', 'nameOrig', 'nameDest', 'step'])\n",
    "y = df['isFraud']\n",
    "\n",
    "# Train-test split\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.2, random_state=42)\n",
    "\n",
    "# Scale\n",
    "scaler = StandardScaler()\n",
    "X_train_scaled = scaler.fit_transform(X_train)\n",
    "X_test_scaled = scaler.transform(X_test)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "42569bb5",
   "metadata": {},
   "source": [
    "## üß™ Step 2: Hyperparameter Tuning"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "788e1bad",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "üîç Tuning Logistic Regression...\n",
      "Best LR params: {'C': 10, 'penalty': 'l2', 'solver': 'liblinear'}\n",
      "ROC AUC: 0.9955687196950602\n"
     ]
    }
   ],
   "source": [
    "from sklearn.model_selection import GridSearchCV, RandomizedSearchCV\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from xgboost import XGBClassifier\n",
    "from lightgbm import LGBMClassifier\n",
    "from sklearn.metrics import roc_auc_score\n",
    "\n",
    "# Logistic Regression\n",
    "print(\"üîç Tuning Logistic Regression...\")\n",
    "lr_params = {'C': [0.01, 0.1, 1, 10], 'penalty': ['l2'], 'solver': ['liblinear']}\n",
    "lr = GridSearchCV(LogisticRegression(class_weight='balanced', max_iter=1000), lr_params, scoring='roc_auc', cv=3)\n",
    "lr.fit(X_train_scaled, y_train)\n",
    "print(\"Best LR params:\", lr.best_params_)\n",
    "print(\"ROC AUC:\", roc_auc_score(y_test, lr.predict_proba(X_test_scaled)[:, 1]))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "97cfd06f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "üîç Tuning Random Forest...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:425: FitFailedWarning: \n",
      "11 fits failed out of a total of 15.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\base.py\", line 1152, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 456, in fit\n",
      "    trees = Parallel(\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\utils\\parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\utils\\parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 188, in _parallel_build_trees\n",
      "    tree.fit(X, y, sample_weight=curr_sample_weight, check_input=False)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\base.py\", line 1152, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\tree\\_classes.py\", line 959, in fit\n",
      "    super()._fit(\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\tree\\_classes.py\", line 295, in _fit\n",
      "    classes_k, y_encoded[:, k] = np.unique(y[:, k], return_inverse=True)\n",
      "  File \"<__array_function__ internals>\", line 200, in unique\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\numpy\\lib\\arraysetops.py\", line 274, in unique\n",
      "    ret = _unique1d(ar, return_index, return_inverse, return_counts,\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\numpy\\lib\\arraysetops.py\", line 359, in _unique1d\n",
      "    inv_idx = np.empty(mask.shape, dtype=np.intp)\n",
      "numpy.core._exceptions._ArrayMemoryError: Unable to allocate 25.9 MiB for an array with shape (3393397,) and data type int64\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "3 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\base.py\", line 1152, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 348, in fit\n",
      "    X, y = self._validate_data(\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\base.py\", line 622, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 1146, in check_X_y\n",
      "    X = check_array(\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 915, in check_array\n",
      "    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\utils\\_array_api.py\", line 380, in _asarray_with_order\n",
      "    array = numpy.asarray(array, order=order, dtype=dtype)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\pandas\\core\\generic.py\", line 1998, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "numpy.core._exceptions._ArrayMemoryError: Unable to allocate 298. MiB for an array with shape (3393398, 23) and data type float32\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "4 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\base.py\", line 1152, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 348, in fit\n",
      "    X, y = self._validate_data(\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\base.py\", line 622, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 1146, in check_X_y\n",
      "    X = check_array(\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 915, in check_array\n",
      "    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\utils\\_array_api.py\", line 380, in _asarray_with_order\n",
      "    array = numpy.asarray(array, order=order, dtype=dtype)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\pandas\\core\\generic.py\", line 1998, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "numpy.core._exceptions._ArrayMemoryError: Unable to allocate 298. MiB for an array with shape (3393397, 23) and data type float32\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\base.py\", line 1152, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 456, in fit\n",
      "    trees = Parallel(\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\utils\\parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\utils\\parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 188, in _parallel_build_trees\n",
      "    tree.fit(X, y, sample_weight=curr_sample_weight, check_input=False)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\base.py\", line 1152, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\tree\\_classes.py\", line 959, in fit\n",
      "    super()._fit(\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\tree\\_classes.py\", line 295, in _fit\n",
      "    classes_k, y_encoded[:, k] = np.unique(y[:, k], return_inverse=True)\n",
      "  File \"<__array_function__ internals>\", line 200, in unique\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\numpy\\lib\\arraysetops.py\", line 274, in unique\n",
      "    ret = _unique1d(ar, return_index, return_inverse, return_counts,\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\numpy\\lib\\arraysetops.py\", line 358, in _unique1d\n",
      "    imask = np.cumsum(mask) - 1\n",
      "  File \"<__array_function__ internals>\", line 200, in cumsum\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\numpy\\core\\fromnumeric.py\", line 2597, in cumsum\n",
      "    return _wrapfunc(a, 'cumsum', axis=axis, dtype=dtype, out=out)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\numpy\\core\\fromnumeric.py\", line 57, in _wrapfunc\n",
      "    return bound(*args, **kwds)\n",
      "numpy.core._exceptions._ArrayMemoryError: Unable to allocate 12.9 MiB for an array with shape (3393397,) and data type int32\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\base.py\", line 1152, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 348, in fit\n",
      "    X, y = self._validate_data(\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\base.py\", line 622, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 1146, in check_X_y\n",
      "    X = check_array(\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 915, in check_array\n",
      "    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\utils\\_array_api.py\", line 380, in _asarray_with_order\n",
      "    array = numpy.asarray(array, order=order, dtype=dtype)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\pandas\\core\\generic.py\", line 1997, in __array__\n",
      "    values = self._values\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\pandas\\core\\frame.py\", line 1001, in _values\n",
      "    return ensure_wrapped_if_datetimelike(self.values)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\pandas\\core\\frame.py\", line 11360, in values\n",
      "    return self._mgr.as_array()\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 1732, in as_array\n",
      "    arr = self._interleave(dtype=dtype, na_value=na_value)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 1768, in _interleave\n",
      "    result = np.empty(self.shape, dtype=dtype)\n",
      "numpy.core._exceptions._ArrayMemoryError: Unable to allocate 595. MiB for an array with shape (23, 3393397) and data type float64\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\base.py\", line 1152, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 348, in fit\n",
      "    X, y = self._validate_data(\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\base.py\", line 622, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 1146, in check_X_y\n",
      "    X = check_array(\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 915, in check_array\n",
      "    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\utils\\_array_api.py\", line 380, in _asarray_with_order\n",
      "    array = numpy.asarray(array, order=order, dtype=dtype)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\pandas\\core\\generic.py\", line 1997, in __array__\n",
      "    values = self._values\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\pandas\\core\\frame.py\", line 1001, in _values\n",
      "    return ensure_wrapped_if_datetimelike(self.values)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\pandas\\core\\frame.py\", line 11360, in values\n",
      "    return self._mgr.as_array()\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 1732, in as_array\n",
      "    arr = self._interleave(dtype=dtype, na_value=na_value)\n",
      "  File \"c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 1768, in _interleave\n",
      "    result = np.empty(self.shape, dtype=dtype)\n",
      "numpy.core._exceptions._ArrayMemoryError: Unable to allocate 595. MiB for an array with shape (23, 3393398) and data type float64\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\israila.dare\\AppData\\Local\\anaconda3\\envs\\diabetes\\lib\\site-packages\\sklearn\\model_selection\\_search.py:979: UserWarning: One or more of the test scores are non-finite: [0.99959351        nan        nan        nan        nan]\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Best RF params: {'n_estimators': 100, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_depth': 10}\n",
      "ROC AUC: 0.9997082704834712\n"
     ]
    }
   ],
   "source": [
    "# Random Forest\n",
    "print(\"üîç Tuning Random Forest...\")\n",
    "rf_params = {\n",
    "    'n_estimators': [100, 200],\n",
    "    'max_depth': [None, 10, 20],\n",
    "    'min_samples_split': [2, 5],\n",
    "    'min_samples_leaf': [1, 2]\n",
    "}\n",
    "rf = RandomizedSearchCV(RandomForestClassifier(class_weight='balanced', random_state=42),\n",
    "                        rf_params, n_iter=5, scoring='roc_auc', cv=3, random_state=42)\n",
    "rf.fit(X_train, y_train)\n",
    "print(\"Best RF params:\", rf.best_params_)\n",
    "print(\"ROC AUC:\", roc_auc_score(y_test, rf.predict_proba(X_test)[:, 1]))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c6b4ab92",
   "metadata": {},
   "outputs": [],
   "source": [
    "# XGBoost\n",
    "print(\"üîç Tuning XGBoost...\")\n",
    "xgb_params = {\n",
    "    'n_estimators': [100, 200],\n",
    "    'max_depth': [3, 6, 10],\n",
    "    'learning_rate': [0.01, 0.1],\n",
    "    'subsample': [0.8, 1.0]\n",
    "}\n",
    "xgb = RandomizedSearchCV(XGBClassifier(use_label_encoder=False, eval_metric='logloss'),\n",
    "                         xgb_params, n_iter=5, scoring='roc_auc', cv=3, random_state=42)\n",
    "xgb.fit(X_train, y_train)\n",
    "print(\"Best XGB params:\", xgb.best_params_)\n",
    "print(\"ROC AUC:\", roc_auc_score(y_test, xgb.predict_proba(X_test)[:, 1]))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4d095fd0",
   "metadata": {},
   "outputs": [],
   "source": [
    "# LightGBM\n",
    "print(\"üîç Tuning LightGBM...\")\n",
    "lgbm_params = {\n",
    "    'n_estimators': [100, 200],\n",
    "    'num_leaves': [31, 50],\n",
    "    'learning_rate': [0.01, 0.1],\n",
    "    'boosting_type': ['gbdt']\n",
    "}\n",
    "lgbm = RandomizedSearchCV(LGBMClassifier(class_weight='balanced'),\n",
    "                          lgbm_params, n_iter=5, scoring='roc_auc', cv=3, random_state=42)\n",
    "lgbm.fit(X_train, y_train)\n",
    "print(\"Best LGBM params:\", lgbm.best_params_)\n",
    "print(\"ROC AUC:\", roc_auc_score(y_test, lgbm.predict_proba(X_test)[:, 1]))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "diabetes",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
